#!/bin/bash
#autorandr -c &
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 1080x133 --rate 165.00 --rotate normal --brightness 1 --output DisplayPort-1 --mode 2560x1440 --pos 3640x133 --rate 165.00 --rotate normal --brightness 1 --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --rate 60.00 --pos 0x0 --rotate left --brightness 1 --output HDMI-A-1-1 --off --output DisplayPort-1-3 --off --output DisplayPort-1-4 --off --output DisplayPort-1-5 --off &
sxhkd -m 1 &
#~/.config/bspwm/screen.sh &
bspc monitor HDMI-A-0 -d 1 2 3
bspc monitor DisplayPort-0 -d 4 5 6 7
bspc monitor DisplayPort-1 -d 8 9 10
fcitx5 -d &
picom --experimental-backend -b --config ~/.config/picom/picom.conf &
#xautolock -time 5 -locker '~/scripts/lockscreen.sh' -corners 0-00 -killtime 20 -killer '/usr/bin/systemctl suspend' -detectsleep -secure &
# xautolock -time 5 -locker '~/scripts/lockscreen.sh' -corners 0-00 -secure &
#xss-lock --transfer-sleep-lock -- betterlockscreen -l &
xsetroot -cursor_name left_ptr &
nm-applet &
~/.config/polybar/launch.sh &
xinput set-prop 24 285 1 &
eval $(ssh-agent) &
bspc config window_gap 2
bspc config normal_border_color "#3B4252"
bspc config active_border_color "#81A1C1"
bspc config focused_border_color "#88C0D0"
bspc config presel-feedback color "#88C0D0"
bspc config top_padding 40
bspc config bottom_padding 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus follows pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp deskt='^7' state=floating follow=on
bspc rule -a firefox desktop='^4' follow=on
bspc rule -a Spotify desktop='^10' follow=on
bspc rule -a discord desktop='^9' follow=on
bspc rule -a ulauncher focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Com.cisco.anyconnect.gui desktop='^10' follow=on

# betterlockscreen -u ~/Pictures/Wallpaper/framework_wallpaper.png &
feh --bg-fill ~/Pictures/Wallpaper/WP_Laser_Up-2560x1440_00229.jpg &
